In [127]:
#Importing Pandas library for cleaning up raw data
import pandas as pd
import numpy as np

In [97]:
#File name of raw csv, which should be in the same folder/directory as the Preprocessing Notebook
raw_filename = 'NCWIT_DataV2_RawData.csv'

In [98]:
rawdata_dataframe = pd.read_csv(raw_filename)
rawdata_dataframe

,Record#,CIP# Only,Major Program Name,Degree Level,NCWIT Participant,Institution,What degrees does your institution offer?,School Year,When do students typically declare their major?,"Enroll, Female: Avg. ACT Math Score (Enrl F)",...,Nonresident Alien (Min. M).1,Race/Ethnicity Unknown (Min. M).1,Nonresident Alien (Min. F).2,Race/Ethnicity Unknown (Min. F).2,Nonresident Alien (Min. M).2,Race/Ethnicity Unknown (Min. M).2,Nonresident Alien (Tot. F),Race/Ethnicity Unknown (Tot. F),Nonresident Alien (Tot. M),Race/Ethnicity Unknown (Tot. M)
0,1231.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2005-2006,End of 2nd Year,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1232.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2006-2007,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1233.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2007-2008,End of 2nd Year,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1234.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2008-2009,End of 2nd Year,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1235.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2009-2010,End of 2nd Year,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1236.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2010-2011,End of 2nd Year,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1237.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2011-2012,End of 2nd Year,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1498.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2004-2005,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1499.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2005-2006,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1500.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2006-2007,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1501.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2007-2008,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1502.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2008-2009,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1503.0,11.01,Computer Science / Engineering,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2009-2010,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2049.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2010-2011,Upon Enrollment,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2050.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2011-2012,Upon Enrollment,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2051.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2012-2013,Upon Enrollment,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2052.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",128.0,"Bachelor's, master's, and Ph.D. degrees",2013-2014,Upon Enrollment,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2079.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2008-2009,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2080.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2009-2010,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2081.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2010-2011,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,13.0,6.0,94.0,69.0
20,2082.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2011-2012,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,16.0,7.0,116.0,56.0
21,2083.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2012-2013,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,22.0,6.0,123.0,52.0
22,2084.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2013-2014,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,30.0,7.0,145.0,56.0
23,2085.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",88.0,"Bachelor's, master's, and Ph.D. degrees",2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,29.0,9.0,152.0,60.0
24,2168.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2004-2005,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2169.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2005-2006,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2170.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2006-2007,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2171.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2007-2008,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2172.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2008-2009,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2173.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Academic Alliance, Academic Alliance",21.0,"Bachelor's, master's, and Ph.D. degrees",2009-2010,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Filter raw data by Program of NCIW Extention Services, Academic Alliances

In [99]:
#Column Name = NCWIT Participant
targetFilter = 'Extension Services, Academic Alliance'
yearFilter =['2007-2008','2009-2010','2010-2011','2011-2012','2012-2013','2013-2014','2014-2015','2015-2016']
new_dataframe = rawdata_dataframe[rawdata_dataframe["NCWIT Participant"].isin([targetFilter]) & rawdata_dataframe["School Year"].isin(yearFilter)]

#Masking
#mask = rawdata_dataframe.isin({'NCWIT Participant': [targetFilter], 'School Year': ['2005-2006', '2006-2007', '2007-2008']})
#rawdata_dataframe.where(mask)

### Calculate Male,Female,Total Enrollment

In [100]:
new_dataframe['Male Enrollment'] = new_dataframe['Totals, Male: Enrolled in DIFFERENT MAJOR (Tot. M)'] + new_dataframe['Totals, Male: Enrolled in SAME MAJOR (Tot. M)'] - new_dataframe['Totals, Male: Graduated (Tot. M)'] - new_dataframe['Enroll, Male: Transfer Students (Enrl M)'] - new_dataframe['Enroll, Male: New Enrollments (Enrl M)']
new_dataframe['Female Enrollment'] = new_dataframe['Totals, Female: Enrolled in DIFFERENT MAJOR (Tot. F)'] + new_dataframe['Totals, Female: Enrolled in SAME MAJOR (Tot. F)'] - new_dataframe['Totals, Female: Graduated (Tot. F)'] - new_dataframe['Enroll, Female: Transfer Students (Enrl F)'] - new_dataframe['Enroll, Female: New Enrollments (Enrl F)']
new_dataframe['Total Enrollment'] = new_dataframe['Female Enrollment'] + new_dataframe['Male Enrollment']

C:\Users\jchin\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\jchin\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\jchin\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [166]:
#Get all Institutions
institutions = new_dataframe.Institution.unique()
print(institutions)

prevYear = None
prevTotEnrollment = None

#create empty/NaN for Retention Calc
new_dataframe['Retention'] = np.nan

for inst in institutions:    
    #get rows of data for each inst
    for i,row in new_dataframe.loc[new_dataframe['Institution'].isin([inst]),:].iterrows():
        #if year is xxx then ..
        #print(prevYear)
        #print(int(new_dataframe.loc[i]["School Year"][:4] ))
        
        #if prevYear is not None:
            #prevYearplus = prevYear + 1
            #print("plus1"+str(prevYearplus))
            
            #bool = int(prevYearplus) == int(new_dataframe.loc[i]["School Year"][:4])
            #print(bool)
        
        if prevYear is None:
           prevYear = int(new_dataframe.loc[i]["School Year"][:4])
           prevTotEnrollment = new_dataframe.loc[i]["Total Enrollment"] 
        elif ( int(prevYear + 1) == int(new_dataframe.loc[i]["School Year"][:4] )):
            print( "got here2")
            curYear = int(new_dataframe.loc[i]["School Year"][:4])
            currTotEnrollment =  new_dataframe.loc[i]["Total Enrollment"] 
            new_dataframe.at[i, 'Retention'] = currTotEnrollment / prevTotEnrollment
            
            #new_dataframe.loc[i]["Retention"]  = 999 #currTotEnrollment / prevTotEnrollment
            #new_dataframe.loc[i]["Retention"]
            #update previous year 
            prevYear = curYear
            prevTotEnrollment = currTotEnrollment         
        else:
            prevYear =  int(new_dataframe.loc[i]["School Year"][:4])
            prevTotEnrollment = new_dataframe.loc[i]["Total Enrollment"]
        
            print('end')
    prevYear = None
    prevTotEnrollment = None

[ 456.  128.   88.  430.  205.  370.   68.  110.   85.  114.  435.  361.
  117.  263.  216.  238.  249.  369.  424.  112.   64.  200.  157.    6.
   13.   54.  487.   29.  388.   72.  302.   82.  422.  287.  462.  131.
  412.  493.   38.   83.  469.  319.   26.  194.  500.  346.   75.  373.
   41.   46.  489.  115.  324.  179.  490.  155.  336.  182.  146.  475.
   97.  437.  123.]
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
end
end
end
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
end
end
end
end
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2

C:\Users\jchin\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
end
end
end
end
end
end
got here2
got here2
got here2
got here2
end
end
end
got here2
got here2
got here2
got here2
end
end
got here2
end
end
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
end
got here2
end
end
got here2
got here2
end
got here2
got here2
got here2
got here2
end
end
end
end
end
end
end
end
end
end
got here2
got here2
got here2
end
got here2
got here2
got here2
end
end
end
end
end
end
got here2
got here2
got here2
end
end
end
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
end
end
end
end
got here2
got here2
end
end
end
got here2
end
end
got here2
got here2
end
got here2
got here2
end
end
got here2
end
end
end
end
got here2
end
end
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
end
got here2
got here2
end
got here2

C:\Users\jchin\Anaconda2\lib\site-packages\ipykernel_launcher.py:32: RuntimeWarning: divide by zero encountered in double_scalars

end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
end
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
end
end
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
got here2
got here2
end
end
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
got here2
end
got here2
end
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
end
end
end
end
end
end
end
got here2
got here2
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
end
end
end
end
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
got here2
end
end
end
end
got here2
got here2
got here2
end
end
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
end
end
end
got here2
got here2
got here2
end
end
end
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
got here2
end
end
end
end
end
end
end
end
end
end
end
end
got here2
got here2
got here2
got here2
end
end
got here2
got here2
got here2
got here2
got here2
got here2
got here2
got here2
end
got here2
got here2
end
got here2
got here2
end
end
end
end
end

In [169]:
#Output results to csv

new_dataframe.to_csv("clean_data.csv", sep='\t')

In [17]:
#Filter Instititions that have records for years (2005,2006,2007)
insts_w_years
years = [2005-2006','2006-2007','2007-200']
for inst in institutions:
    rawdata_dataframe[rawdata_dataframe["Institution"].isin([456.0,72.0]) & rawdata_dataframe["School Year"].isin(years)]

    
    print inst

456.0
128.0
88.0
21.0
323.0
114.0
430.0
205.0
370.0
68.0
314.0
110.0
331.0
481.0
63.0
85.0
435.0
361.0
117.0
263.0
334.0
387.0
216.0
109.0
32.0
320.0
295.0
319.0
440.0
367.0
268.0
47.0
36.0
143.0
497.0
37.0
158.0
238.0
485.0
322.0
173.0
7.0
27.0
249.0
369.0
250.0
368.0
424.0
112.0
393.0
438.0
64.0
499.0
337.0
453.0
236.0
187.0
200.0
157.0
262.0
233.0
65.0
294.0
371.0
333.0
40.0
6.0
13.0
379.0
397.0
224.0
351.0
144.0
154.0
417.0
25.0
291.0
232.0
394.0
82.0
78.0
381.0
43.0
54.0
487.0
29.0
388.0
72.0
302.0
422.0
287.0
462.0
131.0
412.0
493.0
38.0
83.0
469.0
26.0
395.0
297.0
243.0
364.0
223.0
172.0
312.0
411.0
345.0
160.0
127.0
155.0
270.0
459.0
392.0
421.0
348.0
194.0
330.0
87.0
271.0
189.0
217.0
51.0
307.0
260.0
20.0
211.0
60.0
244.0
4.0
91.0
258.0
445.0
133.0
121.0
490.0
201.0
61.0
14.0
9.0
101.0
248.0
500.0
176.0
299.0
124.0
486.0
346.0
75.0
373.0
41.0
46.0
489.0
115.0
467.0
324.0
347.0
148.0
414.0
105.0
179.0
468.0
255.0
443.0
163.0
170.0
326.0
150.0
251.0
137.0
122.0
380.0
410.0
104.0
18.0
90.0
116.0
84.0
451.0
311.0
363.0
336.0
448.0
182.0
146.0
475.0
420.0
97.0
240.0
437.0
476.0
463.0
123.0
204.0
206.0
464.0
134.0
120.0
402.0
nan

In [137]:
print(new_dataframe['Enroll, Male: Transfer Students (Enrl M)'])
print(new_dataframe['Enroll, Female: Transfer Students (Enrl F)'])

2         1.0
4         6.0
5         7.0
6        13.0
10        0.0
12        0.0
13       14.0
14       18.0
15       34.0
16        5.0
18        NaN
19       79.0
20       75.0
21       59.0
22       62.0
23       56.0
35      239.0
36      205.0
37      134.0
38      141.0
39       53.0
40       49.0
42       18.0
47        NaN
49        NaN
53        5.0
54       13.0
55       33.0
56       31.0
57       34.0
        ...
2710     26.0
2712      NaN
2714     11.0
2725     38.0
2726     40.0
2727     87.0
2729      5.0
2730      1.0
2731      2.0
2732      4.0
2733      2.0
2734      8.0
2736     13.0
2737     22.0
2738     18.0
2739     24.0
2740     21.0
2741     16.0
2744      6.0
2745      3.0
2746      3.0
2753     24.0
2754     37.0
2755     30.0
2756     27.0
2757     29.0
2758     51.0
2759     52.0
2792      2.0
2794      1.0
Name: Enroll, Male: Transfer Students (Enrl M), Length: 918, dtype: float64
2        0.0
4        1.0
5        2.0
6        5.0
10       0.0
12       0.0
13       3.0
14       5.0
15       0.0
16       2.0
18       NaN
19       7.0
20       9.0
21       6.0
22      12.0
23      13.0
35      35.0
36      26.0
37      15.0
38      18.0
39      11.0
40       6.0
42       1.0
47       NaN
49       NaN
53       2.0
54       6.0
55       7.0
56       8.0
57       6.0
        ...
2710     2.0
2712     NaN
2714     1.0
2725     9.0
2726     9.0
2727    14.0
2729     2.0
2730     2.0
2731     1.0
2732     2.0
2733     2.0
2734     3.0
2736     1.0
2737     2.0
2738     1.0
2739     4.0
2740     4.0
2741     3.0
2744     0.0
2745     0.0
2746     0.0
2753     4.0
2754     2.0
2755     4.0
2756     3.0
2757     2.0
2758     3.0
2759     9.0
2792     0.0
2794     1.0
Name: Enroll, Female: Transfer Students (Enrl F), Length: 918, dtype: float64

In [168]:
new_dataframe[['Institution','School Year','Totals, Male: Enrolled in DIFFERENT MAJOR (Tot. M)','Totals, Male: Enrolled in SAME MAJOR (Tot. M)' ,'Totals, Male: Graduated (Tot. M)' ,'Enroll, Male: Transfer Students (Enrl M)','Enroll, Male: New Enrollments (Enrl M)','Male Enrollment','Total Enrollment','Retention']][0:50]

,Institution,School Year,"Totals, Male: Enrolled in DIFFERENT MAJOR (Tot. M)","Totals, Male: Enrolled in SAME MAJOR (Tot. M)","Totals, Male: Graduated (Tot. M)","Enroll, Male: Transfer Students (Enrl M)","Enroll, Male: New Enrollments (Enrl M)",Male Enrollment,Total Enrollment,Retention
2,456.0,2007-2008,7.0,34.0,14.0,1.0,12.0,14.0,20.0,NaN
4,456.0,2009-2010,1.0,15.0,12.0,6.0,14.0,-16.0,-18.0,NaN
5,456.0,2010-2011,1.0,20.0,8.0,7.0,11.0,-5.0,-15.0,0.833333
6,456.0,2011-2012,0.0,10.0,17.0,13.0,19.0,-39.0,-49.0,3.266667
10,128.0,2007-2008,49.0,222.0,54.0,0.0,87.0,130.0,131.0,NaN
12,128.0,2009-2010,42.0,223.0,42.0,0.0,112.0,111.0,123.0,NaN
13,128.0,2010-2011,15.0,324.0,61.0,14.0,132.0,132.0,142.0,1.154472
14,128.0,2011-2012,11.0,340.0,58.0,18.0,120.0,155.0,161.0,1.133803
15,128.0,2012-2013,13.0,386.0,57.0,34.0,159.0,149.0,173.0,1.074534
16,128.0,2013-2014,16.0,390.0,75.0,5.0,152.0,174.0,182.0,1.052023
18,88.0,2009-2010,NaN,NaN,NaN,NaN,246.0,NaN,NaN,NaN
19,88.0,2010-2011,15.0,714.0,239.0,79.0,185.0,226.0,270.0,NaN
20,88.0,2011-2012,5.0,721.0,276.0,75.0,183.0,192.0,226.0,0.837037
21,88.0,2012-2013,5.0,761.0,291.0,59.0,182.0,234.0,269.0,1.190265
22,88.0,2013-2014,7.0,746.0,365.0,62.0,218.0,108.0,138.0,0.513011
23,88.0,2014-2015,5.0,743.0,316.0,56.0,174.0,202.0,218.0,1.579710
35,430.0,2014-2015,NaN,NaN,NaN,239.0,446.0,NaN,NaN,NaN
36,430.0,2013-2014,89.0,1187.0,238.0,205.0,355.0,478.0,609.0,NaN
37,430.0,2012-2013,76.0,1001.0,209.0,134.0,464.0,270.0,357.0,NaN
38,430.0,2011-2012,45.0,701.0,177.0,141.0,271.0,157.0,229.0,NaN
39,430.0,2010-2011,56.0,558.0,130.0,53.0,176.0,255.0,316.0,NaN
40,430.0,2009-2010,44.0,478.0,87.0,49.0,168.0,218.0,261.0,NaN
42,430.0,2007-2008,50.0,326.0,110.0,18.0,124.0,124.0,140.0,NaN
47,205.0,2009-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,205.0,2007-2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,456.0,2012-2013,0.0,6.0,7.0,5.0,15.0,-21.0,-30.0,0.612245
54,456.0,2013-2014,0.0,20.0,6.0,13.0,21.0,-20.0,-30.0,1.000000
55,370.0,2013-2014,18.0,126.0,24.0,33.0,48.0,39.0,39.0,NaN
56,370.0,2012-2013,10.0,136.0,19.0,31.0,51.0,45.0,48.0,NaN
57,370.0,2011-2012,9.0,120.0,9.0,34.0,65.0,21.0,21.0,NaN
58,370.0,2010-2011,18.0,85.0,16.0,19.0,45.0,23.0,28.0,NaN
59,370.0,2009-2010,16.0,73.0,17.0,21.0,44.0,7.0,15.0,NaN
64,68.0,2007-2008,48.0,391.0,141.0,40.0,149.0,109.0,137.0,NaN
66,68.0,2009-2010,40.0,403.0,135.0,42.0,132.0,134.0,190.0,NaN
67,68.0,2010-2011,28.0,404.0,147.0,69.0,192.0,24.0,63.0,0.331579
68,68.0,2011-2012,31.0,510.0,162.0,92.0,287.0,0.0,53.0,0.841270
69,68.0,2012-2013,49.0,639.0,140.0,86.0,309.0,153.0,221.0,4.169811
70,68.0,2013-2014,55.0,897.0,195.0,131.0,469.0,157.0,261.0,1.180995
71,68.0,2014-2015,70.0,1077.0,256.0,183.0,554.0,154.0,298.0,1.141762
72,68.0,2015-2016,89.0,1218.0,303.0,153.0,435.0,416.0,546.0,1.832215
73,128.0,2014-2015,48.0,340.0,47.0,40.0,214.0,87.0,90.0,0.494505
74,88.0,2015-2016,0.0,783.0,322.0,62.0,214.0,185.0,242.0,1.110092
76,110.0,2009-2010,43.0,355.0,59.0,21.0,132.0,186.0,220.0,NaN
77,110.0,2010-2011,59.0,423.0,66.0,28.0,184.0,204.0,242.0,1.100000
78,110.0,2011-2012,68.0,481.0,73.0,24.0,192.0,260.0,291.0,1.202479
79,110.0,2012-2013,74.0,515.0,88.0,25.0,182.0,294.0,333.0,1.144330
80,110.0,2013-2014,65.0,587.0,99.0,46.0,214.0,293.0,322.0,0.966967
81,110.0,2014-2015,56.0,459.0,103.0,49.0,49.0,314.0,365.0,1.133540
85,110.0,2015-2016,41.0,526.0,129.0,53.0,53.0,332.0,377.0,1.032877
87,370.0,2014-2015,8.0,106.0,28.0,28.0,56.0,2.0,6.0,NaN

In [135]:
new_dataframe[['Institution','School Year','Totals, Female: Enrolled in DIFFERENT MAJOR (Tot. F)','Totals, Female: Enrolled in SAME MAJOR (Tot. F)' ,'Totals, Female: Graduated (Tot. F)' ,'Enroll, Female: Transfer Students (Enrl F)','Enroll, Female: New Enrollments (Enrl F)','Female Enrollment','Retention']][0:30]

,Institution,School Year,"Totals, Female: Enrolled in DIFFERENT MAJOR (Tot. F)","Totals, Female: Enrolled in SAME MAJOR (Tot. F)","Totals, Female: Graduated (Tot. F)","Enroll, Female: Transfer Students (Enrl F)","Enroll, Female: New Enrollments (Enrl F)",Female Enrollment,Retention
2,456.0,2007-2008,4.0,8.0,4.0,0.0,2.0,6.0,NaN
4,456.0,2009-2010,0.0,9.0,6.0,1.0,4.0,-2.0,NaN
5,456.0,2010-2011,0.0,2.0,7.0,2.0,3.0,-10.0,NaN
6,456.0,2011-2012,1.0,4.0,3.0,5.0,7.0,-10.0,NaN
10,128.0,2007-2008,0.0,12.0,10.0,0.0,1.0,1.0,NaN
12,128.0,2009-2010,8.0,23.0,2.0,0.0,17.0,12.0,NaN
13,128.0,2010-2011,1.0,28.0,7.0,3.0,9.0,10.0,NaN
14,128.0,2011-2012,1.0,28.0,3.0,5.0,15.0,6.0,NaN
15,128.0,2012-2013,0.0,41.0,4.0,0.0,13.0,24.0,NaN
16,128.0,2013-2014,1.0,34.0,10.0,2.0,15.0,8.0,NaN
18,88.0,2009-2010,NaN,NaN,NaN,NaN,34.0,NaN,NaN
19,88.0,2010-2011,1.0,99.0,21.0,7.0,28.0,44.0,NaN
20,88.0,2011-2012,1.0,95.0,35.0,9.0,18.0,34.0,NaN
21,88.0,2012-2013,0.0,104.0,40.0,6.0,23.0,35.0,NaN
22,88.0,2013-2014,1.0,113.0,42.0,12.0,30.0,30.0,NaN
23,88.0,2014-2015,0.0,112.0,51.0,13.0,32.0,16.0,NaN
35,430.0,2014-2015,NaN,NaN,NaN,35.0,84.0,NaN,NaN
36,430.0,2013-2014,32.0,238.0,54.0,26.0,59.0,131.0,NaN
37,430.0,2012-2013,31.0,206.0,43.0,15.0,92.0,87.0,NaN
38,430.0,2011-2012,22.0,149.0,31.0,18.0,50.0,72.0,NaN
39,430.0,2010-2011,21.0,114.0,22.0,11.0,41.0,61.0,NaN
40,430.0,2009-2010,18.0,88.0,25.0,6.0,32.0,43.0,NaN
42,430.0,2007-2008,12.0,42.0,20.0,1.0,17.0,16.0,NaN
47,205.0,2009-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,205.0,2007-2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,456.0,2012-2013,0.0,1.0,5.0,2.0,3.0,-9.0,NaN
54,456.0,2013-2014,1.0,8.0,5.0,6.0,8.0,-10.0,NaN
55,370.0,2013-2014,7.0,19.0,5.0,7.0,14.0,0.0,NaN
56,370.0,2012-2013,4.0,20.0,2.0,8.0,11.0,3.0,NaN
57,370.0,2011-2012,5.0,23.0,3.0,6.0,19.0,0.0,NaN

In [6]:
def getColumnData(colname):
    return rawdata_dataframe[colname]

#example
getColumnData('Record#')

0       1231.0
1       1232.0
2       1233.0
3       1234.0
4       1235.0
5       1236.0
6       1237.0
7       1498.0
8       1499.0
9       1500.0
10      1501.0
11      1502.0
12      1503.0
13      2049.0
14      2050.0
15      2051.0
16      2052.0
17      2079.0
18      2080.0
19      2081.0
20      2082.0
21      2083.0
22      2084.0
23      2085.0
24      2168.0
25      2169.0
26      2170.0
27      2171.0
28      2172.0
29      2173.0
         ...
3875       NaN
3876       NaN
3877       NaN
3878       NaN
3879       NaN
3880       NaN
3881       NaN
3882       NaN
3883       NaN
3884       NaN
3885       NaN
3886       NaN
3887       NaN
3888       NaN
3889       NaN
3890       NaN
3891       NaN
3892       NaN
3893       NaN
3894       NaN
3895       NaN
3896       NaN
3897       NaN
3898       NaN
3899       NaN
3900       NaN
3901       NaN
3902       NaN
3903       NaN
3904       NaN
Name: Record#, Length: 3905, dtype: float64

In [11]:
#Filter Column by string and remove NaN (null or Not a Number values in data)

def filterColByStr(colname,string_filter):
    return rawdata_dataframe[rawdata_dataframe[colname].str.contains(string_filter, na = False )]

#Step-by-step explanation (from inner to outer):
#df['column name'] selects the ids column of the data frame (techincally, the object df[ids] is of type pandas.Series)
#df['ids'].str allows us to apply vectorized string methods (e.g., lower, contains) to the Series
#df['ids'].str.contains('') checks each element of the Series as to whether the element value has the string filter as a substring. The result is a Series of Booleans indicating True or False about the existence of a 'ball' substring.
#df[df['ids'].str.contains('ball')] applies the Boolean 'mask' to the dataframe and returns a view containing appropriate records.
#na = False removes NA / NaN values from consideration; otherwise a ValueError may be returned.
 
filterColByStr('What degrees does your institution offer?',"Bachelor's and master's degrees only")

,Record#,CIP# Only,Major Program Name,Degree Level,NCWIT Participant,Institution,What degrees does your institution offer?,School Year,When do students typically declare their major?,"Enroll, Female: Avg. ACT Math Score (Enrl F)",...,Nonresident Alien (Min. M).1,Race/Ethnicity Unknown (Min. M).1,Nonresident Alien (Min. F).2,Race/Ethnicity Unknown (Min. F).2,Nonresident Alien (Min. M).2,Race/Ethnicity Unknown (Min. M).2,Nonresident Alien (Tot. F),Race/Ethnicity Unknown (Tot. F),Nonresident Alien (Tot. M),Race/Ethnicity Unknown (Tot. M)
0,1231.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2005-2006,End of 2nd Year,27.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1232.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2006-2007,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1233.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2007-2008,End of 2nd Year,27.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1234.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2008-2009,End of 2nd Year,31.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1235.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2009-2010,End of 2nd Year,27.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1236.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2010-2011,End of 2nd Year,24.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1237.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2011-2012,End of 2nd Year,26.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,4242.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2012-2013,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0
54,4243.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2013-2014,End of 2nd Year,23.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,4.0
55,4267.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2013-2014,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,15.0
56,4268.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2012-2013,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,14.0
57,4269.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2011-2012,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,13.0
58,4270.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2010-2011,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,11.0
59,4271.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2009-2010,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,20.0
87,4943.0,11.01,Computer and Information Sciences,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,10.0
88,4944.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2015-2016,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,27.0
89,4945.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",370.0,Bachelor's and master's degrees only,2016-2017,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,24.0
100,1258.0,11.0103,Applied Information Technology,Bachelor's,"Extension Services, Academic Alliance",85.0,Bachelor's and master's degrees only,2012-2013,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,2010.0,11.0103,Applied Information Technology,Bachelor's,"Extension Services, Academic Alliance",85.0,Bachelor's and master's degrees only,2013-2014,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,2716.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2009-2010,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN
229,4439.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2015-2016,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,6.0
230,4442.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2012-2013,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,9.0
231,4443.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2013-2014,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,5.0
232,4444.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2014-2015,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,2.0,5.0
233,4534.0,11.0103,Information Technology,Bachelor's,Academic Alliance,485.0,Bachelor's and master's degrees only,2015-2016,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,4563.0,11.0103,Information Technology,Bachelor's,"Academic Alliance, IPEDS",295.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,15.0,2.0
245,5047.0,11.0103,Information Technology,Bachelor's,Academic Alliance,320.0,Bachelor's and master's degrees only,2004-2005,End of 1st Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.0,NaN
291,4565.0,11.0104,Informatics,Bachelor's,"Academic Alliance, IPEDS",295.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
644,4479.0,11.05,Computer Information Systems,Bachelor's,Academic Alliance,485.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,4481.0,11.05,Computer Information Systems,Bachelor's,Academic Alliance,43.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2338,4029.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2013-2014,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2339,4036.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2012-2013,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2340,4042.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2011-2012,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2341,4048.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2010-2011,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2342,4054.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2009-2010,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2369,4516.0,14.0900,Computer Engineering,Bachelor'ss,Academic Alliance,476.0,Bachelor's and master's degrees only,2015-2016,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2377,4861.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2015-2016,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2378,4862.0,14.0900,Computer Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2016-2017,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2446,4435.0,14.0903,Software Engineering,Bachelor's,Academic Alliance,463.0,Bachelor's and master's degrees only,2015-2016,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527,4024.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2528,4030.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2013-2014,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2529,4037.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2012-2013,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2530,4043.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2011-2012,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2531,4049.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2010-2011,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2532,4055.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2009-2010,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2594,4859.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2015-2016,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,12.0,1.0
2595,4860.0,14.1000,Electrical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2016-2017,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,2.0
2671,4025.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2014-2015,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2672,4031.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2013-2014,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2673,4038.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2012-2013,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2674,4044.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2011-2012,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2675,4050.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2010-2011,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2676,4056.0,14.1900,Mechanical Engineering,Bachelor's,"Extension Services, Academic Alliance",75.0,Bachelor's and master's degrees only,2009-2010,Other,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2885,4561.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,295.0,Bachelor's and master's degrees only,2014-2015,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,0.0
2887,4712.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,206.0,Bachelor's and master's degrees only,2014-2015,Upon Enrollment,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,3.0,26.0,8.0
2888,4713.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,143.0,Bachelor's and master's degrees only,2015-2016,Other,22.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890,4805.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,120.0,Bachelor's and master's degrees only,2011-2012,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2891,4806.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,120.0,Bachelor's and master's degrees only,2012-2013,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2892,4808.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,120.0,Bachelor's and master's degrees only,2013-2014,Other,21.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2893,4809.0,52.1200,Management Information Systems,Bachelor's,Academic Alliance,120.0,Bachelor's and master's degrees only,2014-2015,Other,18.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Filter Multiple columns based on numbers or strings
#searching for integer 456.0 in "Institution" column AND '2005-2006' in "School Year" Column
rawdata_dataframe[rawdata_dataframe["Institution"].isin([456.0]) & rawdata_dataframe["School Year"].isin(['2005-2006','2006-2007'])]

,Record#,CIP# Only,Major Program Name,Degree Level,NCWIT Participant,Institution,What degrees does your institution offer?,School Year,When do students typically declare their major?,"Enroll, Female: Avg. ACT Math Score (Enrl F)",...,Nonresident Alien (Min. M).1,Race/Ethnicity Unknown (Min. M).1,Nonresident Alien (Min. F).2,Race/Ethnicity Unknown (Min. F).2,Nonresident Alien (Min. M).2,Race/Ethnicity Unknown (Min. M).2,Nonresident Alien (Tot. F),Race/Ethnicity Unknown (Tot. F),Nonresident Alien (Tot. M),Race/Ethnicity Unknown (Tot. M)
0,1231.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2005-2006,End of 2nd Year,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1232.0,11.01,CS and/or Eng Multiple Majors (data submitted ...,Bachelor's,"Extension Services, Academic Alliance",456.0,Bachelor's and master's degrees only,2006-2007,End of 2nd Year,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [171]:
#searching for integers 456.0 , 72.0 in "Institution" column AND '2005-2006' in "School Year" Column
new_dataframe[new_dataframe["Institution"].isin([6])]

,Record#,CIP# Only,Major Program Name,Degree Level,NCWIT Participant,Institution,What degrees does your institution offer?,School Year,When do students typically declare their major?,"Enroll, Female: Avg. ACT Math Score (Enrl F)",...,Nonresident Alien (Min. M).2,Race/Ethnicity Unknown (Min. M).2,Nonresident Alien (Tot. F),Race/Ethnicity Unknown (Tot. F),Nonresident Alien (Tot. M),Race/Ethnicity Unknown (Tot. M),Male Enrollment,Female Enrollment,Total Enrollment,Retention
480,5340.0,11.04,Information Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2013-2014,Upon Enrollment,NaN,...,NaN,NaN,13.0,1.0,40.0,7.0,149.0,22.0,171.0,NaN
481,5341.0,11.04,Information Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2014-2015,Upon Enrollment,NaN,...,NaN,NaN,10.0,1.0,37.0,6.0,148.0,21.0,169.0,0.988304
482,5342.0,11.04,Information Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2015-2016,Upon Enrollment,NaN,...,NaN,NaN,11.0,0.0,37.0,4.0,159.0,34.0,193.0,1.142012
1721,5336.0,11.07,Computer Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2013-2014,Upon Enrollment,26.0,...,NaN,NaN,24.0,0.0,102.0,11.0,437.0,68.0,505.0,NaN
1722,5337.0,11.07,Computer Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2014-2015,Upon Enrollment,26.0,...,NaN,NaN,24.0,0.0,131.0,14.0,494.0,81.0,575.0,1.138614
1723,5354.0,11.07,Computer Science,Bachelor's,"Extension Services, Academic Alliance",6.0,"Bachelor's, master's, and Ph.D. degrees",2015-2016,Upon Enrollment,25.0,...,NaN,NaN,26.0,0.0,168.0,13.0,559.0,92.0,651.0,1.132174

In [8]:
#Output results to csv

#Filtered for Institutions 456,72.0 for years 2005-2006
cleaned_data_filter1 = rawdata_dataframe[rawdata_dataframe["Institution"].isin([456.0,72.0]) &rawdata_dataframe["School Year"].isin(['2005-2006'])]

#Filtered for Records# > 3000.0 and for years 2005-2006
cleaned_data_filter2 = rawdata_dataframe[  (rawdata_dataframe["Record#"] > 3000.0)  & rawdata_dataframe["School Year"].isin(['2005-2006'])]

print(cleaned_data_filter2["School Year"])

new_dataframe =  pd.DataFrame()
new_dataframe = new_dataframe.append(cleaned_data_filter1)
new_dataframe = new_dataframe.append(cleaned_data_filter2)

new_dataframe.to_csv("clean_data.csv", sep='\t')

44      2005-2006
51      2005-2006
62      2005-2006
162     2005-2006
169     2005-2006
175     2005-2006
183     2005-2006
196     2005-2006
204     2005-2006
212     2005-2006
285     2005-2006
346     2005-2006
414     2005-2006
422     2005-2006
437     2005-2006
445     2005-2006
455     2005-2006
591     2005-2006
599     2005-2006
606     2005-2006
612     2005-2006
618     2005-2006
626     2005-2006
633     2005-2006
639     2005-2006
1141    2005-2006
1144    2005-2006
1150    2005-2006
1156    2005-2006
1175    2005-2006
          ...
1766    2005-2006
1777    2005-2006
1846    2005-2006
1854    2005-2006
1907    2005-2006
1947    2005-2006
1955    2005-2006
1963    2005-2006
2014    2005-2006
2021    2005-2006
2029    2005-2006
2037    2005-2006
2045    2005-2006
2052    2005-2006
2070    2005-2006
2092    2005-2006
2280    2005-2006
2282    2005-2006
2287    2005-2006
2293    2005-2006
2298    2005-2006
2317    2005-2006
2324    2005-2006
2332    2005-2006
2819    2005-2006
2853    2005-2006
2859    2005-2006
2866    2005-2006
2876    2005-2006
2903    2005-2006
Name: School Year, Length: 98, dtype: object